### ISSUE TITLE
Animechan demo not working

### ISSUE THREAD

**Issue by d9k** [public-api-lists/public-api-lists#109]
https://animechan.vercel.app/docs

**Comment by Vaporjawn** [comment]
<img width="582" alt="image" src="https://github.com/public-api-lists/public-api-lists/assets/15694665/13f12a9e-1fbb-495b-ae8b-86bd5b8b48ac">

**Comment by Vaporjawn** [comment]
Are these the new anime chan links? Not sure if his is the same thing 

https://animechan.xyz/

https://github.com/rocktimsaikia/anime-chan
