### ISSUE TITLE
Table Format Issue in README.md under Development section

### ISSUE THREAD

**Issue by DigantGoradia** [public-api-lists/public-api-lists#119]
The table content in README.md is not formatted under Development section.

![image](https://github.com/public-api-lists/public-api-lists/assets/13499153/64217385-5480-4141-af52-be2df28eac6c)

**Comment by DigantGoradia** [comment]
Raised PR #120 to resolve this issue.

**Comment by k4sud0n** [comment]
Thanks 👍
