### ISSUE TITLE
Darksky Weather

### ISSUE THREAD

**Issue by mrincntrl** [public-api-lists/public-api-lists#184]
Darksky Weather API was acquired by Apple a few years ago. They allowed only existing free calls, but just suspended those as well. 

Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

**Comment by DrPanayioths** [comment]
Thank You Very Much @mrincntrl for making an issue about this api, i create a pull request #196  to remove this api
