### ISSUE TITLE
Email (LabStack) link or site is broken

### ISSUE THREAD

**Issue by IAFahim** [public-api-lists/public-api-lists#36]
Source in Readme.MD
![image](https://user-images.githubusercontent.com/63500913/154787290-e5655bc0-7c99-4f7e-be36-56610165b3e6.png)

Redirected link:
https://labstack.com/email
![image](https://user-images.githubusercontent.com/63500913/154787325-a308ee4b-beda-460b-8229-efebbfddedd8.png)

**Comment by DrPanayioths** [comment]
#122
