### ISSUE TITLE
CircleCI API (v1) will be deprecated, CircleCI API (v2) is available 

### ISSUE THREAD

**Issue by IAFahim** [public-api-lists/public-api-lists#37]
Source in ReadME.md
![image](https://user-images.githubusercontent.com/63500913/154787404-76b7f99a-82c6-43a8-b079-27a183aaeb34.png)

Problem:
https://circleci.com/docs/api/#circleci-v1-api-overview
![image](https://user-images.githubusercontent.com/63500913/154787464-6b94767e-6b22-4c08-96b3-82c9d4e695a4.png)

Requested new link to considered:
https://circleci.com/docs/api/v2/
![image](https://user-images.githubusercontent.com/63500913/154787485-f985382d-92d8-4a19-8175-225c577d3e1d.png)

**Comment by DrPanayioths** [comment]
#122
