### ISSUE TITLE
Breaking Bad API is down

### ISSUE THREAD

**Issue by nsde** [public-api-lists/public-api-lists#85]
https://breakingbadapi.com/ is for sale.
It should be removed, right?

**Comment by ashishjaswal2002** [comment]
It should be removed due to copy right content. My application didn't fetch the api it told me this is unauthorized request even website didn't exist

**Comment by nsde** [comment]
This repo isn't maintained anymore, I think. :/

**Comment by DrPanayioths** [comment]
#122

**Comment by ashishjaswal2002** [comment]
@nsde yes it is.
