### ISSUE TITLE
MetaWeather down?

### ISSUE THREAD

**Issue by Imageman** [public-api-lists/public-api-lists#86]
[MetaWeather](https://www.metaweather.com/api/) down?

**Comment by DrPanayioths** [comment]
Meta Weather Is Not Working Anymore As I Check

**Comment by Vaporjawn** [comment]
<img width="835" alt="Screenshot 2023-12-13 at 1 43 46 AM" src="https://github.com/public-api-lists/public-api-lists/assets/15694665/fd6f83ee-13a7-40d7-85d8-b33735a53659">
